### ISSUE TITLE
It works then randomly stops working and returns the following error tested on 2 systems

### ISSUE THREAD

**Issue by eliransapir** [itayperl/mako-dl#5]
Elirans-Mac-mini:mako-dl-master eliransapir$ ./mako
Traceback (most recent call last):
  File "./mako", line 3, in <module>
    import libmako
  File "/Users/eliransapir/Downloads/mako-dl-master/libmako.py", line 58, in <module>
    load_config()
  File "/Users/eliransapir/Downloads/mako-dl-master/libmako.py", line 50, in load_config
    url = vod_config.find(key).text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

![mako-dl-master_ _-bash_ _127x23](https://user-images.githubusercontent.com/1276151/30252270-07b5361e-963d-11e7-9e28-f514cc9bf843.png)

**Comment by itayperl** [comment]
Works fine here...
